const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Nike Shoes',
            category: 'Shoes',
            image: '/images/p2.jpg',
            price: 12000,
            brand: 'Nike',
            rating: 4.7,
            numReviews: 1,
            description: 'high quality shoes',
        },
        {
            _id: '3',
            name: 'Slim TShirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 100,
            brand: 'Local',
            rating: 2.56,
            numReviews: 10,
            description: 'decent quality product',
        },
        {
            _id: '4',
            name: 'Adidas Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 180,
            brand: 'Nike',
            rating: 3.47,
            numReviews: 6,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Blue Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 150,
            brand: 'Nike',
            rating: 2.03,
            numReviews: 3,
            description: 'good shirt',
        },
        {
            _id: '6',
            name: 'Earrings',
            category: 'Ornaments',
            image: '/images/p2.jpg',
            price: 12000,
            brand: 'PNJ',
            rating: 5,
            numReviews: 3,
            description: 'high quality earrings',
        },
        {
            _id: '7',
            name: 'Ring',
            category: 'Ornaments',
            image: '/images/p2.jpg',
            price: 42000,
            brand: 'PNJ',
            rating: 4.4567,
            numReviews: 13,
            description: 'high quality ring',
        }
    ],
};


export default data;